<?php
GLOBAL $swift_font_defaults;
$swift_font_defaults = array(
    'body_font_enable' => FALSE,
    'body_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'body_font_size' => '16',
    'body_font_size_unit' => 'px',
    'body_font_lh' => '1.625',
    'body_font_lh_unit' => 'em',
    'body_font_weight' => 'normal',
    'body_font_transform' => 'none',
    'body_font_style' => 'normal',


    'blog_name_font_enable' => FALSE,
    'blog_name_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'blog_name_font_size' => '3',
    'blog_name_font_size_unit' => 'em',
    'blog_name_font_lh' => '1',
    'blog_name_font_lh_unit' => 'em',
    'blog_name_font_weight' => 'bolder',
    'blog_name_font_transform' => 'none',
    'blog_name_font_style' => 'normal',


    'blog_tagline_font_enable' => FALSE,
    'blog_tagline_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'blog_tagline_font_size' => '1',
    'blog_tagline_font_size_unit' => 'em',
    'blog_tagline_font_lh' => '1',
    'blog_tagline_font_lh_unit' => 'em',
    'blog_tagline_font_weight' => 'normal',
    'blog_tagline_font_transform' => 'none',
    'blog_tagline_font_style' => 'normal',


    'nav_a_font_enable' => TRUE,
    'nav_a_font_family' => 'Arial, "Helvetica Neue", Helvetica, sans-serif',
    'nav_a_font_size' => '12',
    'nav_a_font_size_unit' => 'px',
    'nav_a_font_lh' => '1.625',
    'nav_a_font_lh_unit' => 'em',
    'nav_a_font_weight' => 'normal',
    'nav_a_font_transform' => 'none',
    'nav_a_font_style' => 'normal',


    'nav_b_font_enable' => TRUE,
    'nav_b_font_family' => 'Arial, "Helvetica Neue", Helvetica, sans-serif',
    'nav_b_font_size' => '12',
    'nav_b_font_size_unit' => 'px',
    'nav_b_font_lh' => '1.625',
    'nav_b_font_lh_unit' => 'em',
    'nav_b_font_weight' => 'normal',
    'nav_b_font_transform' => 'none',
    'nav_b_font_style' => 'normal',

    'home_post_title_enable' => FALSE,
    'home_post_title_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'home_post_title_size' => '1.8',
    'home_post_title_size_unit' => 'em',
    'home_post_title_lh' => '1.625',
    'home_post_title_lh_unit' => 'em',
    'home_post_title_weight' => 'bolder',
    'home_post_title_transform' => 'none',
    'home_post_title_style' => 'normal',


    'home_post_title_mag_enable' => FALSE,
    'home_post_title_mag_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'home_post_title_mag_size' => '1.2',
    'home_post_title_mag_size_unit' => 'em',
    'home_post_title_mag_lh' => '1.625',
    'home_post_title_mag_lh_unit' => 'em',
    'home_post_title_mag_weight' => 'bolder',
    'home_post_title_mag_transform' => 'none',
    'home_post_title_mag_style' => 'normal',

    'single_post_title_enable' => FALSE,
    'single_post_title_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'single_post_title_size' => '2.4',
    'single_post_title_size_unit' => 'em',
    'single_post_title_lh' => '1.25',
    'single_post_title_lh_unit' => 'em',
    'single_post_title_weight' => 'bolder',
    'single_post_title_transform' => 'none',
    'single_post_title_style' => 'normal',

    'heading_tags_enable' => FALSE,
    'heading_tags_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'heading_tags_size' => '16',
    'heading_tags_size_unit' => 'px',
    'heading_tags_lh' => '1.625',
    'heading_tags_lh_unit' => 'em',
    'heading_tags_weight' => 'normal',
    'heading_tags_transform' => 'none',
    'heading_tags_style' => 'normal',


    'post_meta_font_enable' => FALSE,
    'post_meta_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'post_meta_font_size' => '.8',
    'post_meta_font_size_unit' => 'em',
    'post_meta_font_lh' => '1.625',
    'post_meta_font_lh_unit' => 'em',
    'post_meta_font_weight' => 'normal',
    'post_meta_font_transform' => 'uppercase',
    'post_meta_font_style' => 'normal',


    'sidebar_title_font_enable' => FALSE,
    'sidebar_title_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'sidebar_title_font_size' => '1.2',
    'sidebar_title_font_size_unit' => 'em',
    'sidebar_title_font_lh' => '1.625',
    'sidebar_title_font_lh_unit' => 'em',
    'sidebar_title_font_weight' => 'normal',
    'sidebar_title_font_transform' => 'none',
    'sidebar_title_font_style' => 'normal',


    'sidebar_widget_font_enable' => FALSE,
    'sidebar_widget_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'sidebar_widget_font_size' => '1',
    'sidebar_widget_font_size_unit' => 'em',
    'sidebar_widget_font_lh' => '1.625',
    'sidebar_widget_font_lh_unit' => 'em',
    'sidebar_widget_font_weight' => 'normal',
    'sidebar_widget_font_transform' => 'none',
    'sidebar_widget_font_style' => 'normal',


    'footer_title_font_enable' => FALSE,
    'footer_title_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'footer_title_font_size' => '1.2',
    'footer_title_font_size_unit' => 'em',
    'footer_title_font_lh' => '1.625',
    'footer_title_font_lh_unit' => 'em',
    'footer_title_font_weight' => 'normal',
    'footer_title_font_transform' => 'none',
    'footer_title_font_style' => 'normal',


    'footer_widget_font_enable' => FALSE,
    'footer_widget_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'footer_widget_font_size' => '1',
    'footer_widget_font_size_unit' => 'em',
    'footer_widget_font_lh' => '1.625',
    'footer_widget_font_lh_unit' => 'em',
    'footer_widget_font_weight' => 'normal',
    'footer_widget_font_transform' => 'none',
    'footer_widget_font_style' => 'normal',


    'copyright_font_enable' => FALSE,
    'copyright_font_family' => 'Georgia, Palatino," Palatino Linotype", Times, "Times New Roman", serif',
    'copyright_font_size' => '.8',
    'copyright_font_size_unit' => 'em',
    'copyright_font_lh' => '1.625',
    'copyright_font_lh_unit' => 'em',
    'copyright_font_weight' => 'normal',
    'copyright_font_transform' => 'none',
    'copyright_font_style' => 'normal',

)
?>